[project]
name = "judge_htr"
description = "Code repo for 'Judge a book by its cover' paper"
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"